name: atomic-core
description: A core plugin designed for the Atomic Hive Minecraft server.
main: net.atomichive.core.Main
version: 0.1.3
authors: [Sean Bailey]
website: http://atomichive.net
depends: [ProtocolLib]

commands:
  clear:
    description: Clears the target player's inventory.
    usage: /clear [player]
    aliases: [empty, ci]
  entity:
    description: Used to manage Atomic Entities.
    usage: /entity [reload|list|spawn]
    aliases: [ae]
  experience:
    description: Gives experience.
    usage: /xp <experience>
    aliases: [xp]
  fly:
    description: Toggles whether a player can fly.
    usage: /fly [player]
  gamemode:
    description: Updates a player's game mode.
    usage: /gamemode <mode> [player]
    aliases: [gm, mode]
  god:
    description: Toggles god mode.
    usage: /god
  heal:
    description: Restores health and hunger.
    usage: /heal
  item:
    description: Give an item to the specified player.
    usage: /item [player] <material> [amount]
    aliases: [give, i]
  jump:
    description: Jump to the block you're looking at.
    usage: /jump
    aliases: [j]
  kill:
    description: Kills a player.
    usage: /kill <player>
  killall:
    description: Kills all entities, except players.
    usage: /killall [radius]
  level:
    description: A debug command for setting a players level.
    usage: /level <value>
  listen:
    description: Change command listening levels.
    usage: /listen <verbosity(0-2)>
  message:
    description: Send a private message.
    usage: /msg <player> <message>
    aliases: [msg, tell]
  nick:
    description: Set your a custom display name.
    usage: /nick [player] <name...>
  ping:
    description: Returns the delay between a players and the server in milliseconds.
    usage: /ping [player]
    aliases: [delay]
  position:
    description: Returns your current position and the position of the block you're looking at.
    usage: /pos [player]
    aliases: [pos]
  reply:
    description: Respond to the last message you received.
    usage: /reply <message>
    aliases: [r]
  speed:
    description: Change your flying or walking speeds.
    usage: /speed <value>
  sudo:
    description: Run a command as another player.
    usage: /sudo <player> <command>
  suicide:
    description: Causes the player to spontaneously combust.
    usage: /suicide
    aliases: [sepaku]
  teleport:
    description: Teleports one player to another.
    usage: /tp [source] <destination>
    aliases: [tp, tpsilent]
  tpa:
    description: Sends a teleport request to another player.
    usage: /tpa <player>
    aliases: [tprequest, tpask]
  tpaccept:
    description: Accepts the most recent teleport request.
    usage: /tpaccept
    aliases: [tpyes, accept]
  tpall:
    description: Teleports all players to you.
    usage: /tpall
  tpdeny:
    description: Denies the most recent teleport request.
    usage: /tpdeny
    aliases: [tpno, deny]
  tphere:
    description: Teleports another player to you.
    usage: /tphere <player>
    aliases: [tph]
  tppos:
    description: Teleport to a position in your current world.
    usage: /tppos <x> [y] <z>
    aliases: [tpos]
  warp:
    description: Designate a warp destination, or warp somewhere.
    usage: /warp [list|add|remove] [warp]
    aliases: [warps]

permissions:
  atomic-core.*:
    description: Gives access to all atomic-core commands.
    children:
      atomic-core.clear: true
      atomic-core.clear.others: true
      atomic-core.entity: true
      atomic-core.experience: true
      atomic-core.fly: true
      atomic-core.fly.other: true
      atomic-core.gamemode: true
      atomic-core.gamemode.*: true
      atomic-core.gamemode.others: true
      atomic-core.god: true
      atomic-core.heal: true
      atomic-core.item: true
      atomic-core.jump: true
      atomic-core.kill: true
      atomic-core.killall: true
      atomic-core.killall.world: true
      atomic-core.level: true
      atomic-core.listen: true
      atomic-core.message: true
      atomic-core.message.reply: true
      atomic-core.nick: true
      atomic-core.nick.others: true
      atomic-core.ping: true
      atomic-core.ping.others: true
      atomic-core.position: true
      atomic-core.position.others: true
      atomic-core.speed: true
      atomic-core.sudo: true
      atomic-core.suicide: true
      atomic-core.tp: true
      atomic-core.tp.all: true
      atomic-core.tp.here: true
      atomic-core.tp.others: true
      atomic-core.tp.pos: true
      atomic-core.tp.request: true
      atomic-core.tp.silent: true
      atomic-core.warp: true

  atomic-core.clear:
    description: Gives access to the clear command.
    default: op
  atomic-core.clear.others:
    description: Allows a user to clear someone else's inventory.
    default: op

  atomic-core.entity:
    description: Gives access to the entity command.
    default: op

  atomic-core.experience:
    description: Gives access to the xp command.
    default: op

  atomic-core.fly:
    description: Gives access to the fly command.
    default: op
  atomic-core.fly.others:
    description: Allows a user to toggle whether a different player can fly.
    default: op

  atomic-core.gamemode:
    description: Sets a users game mode.
    default: op
  atomic-core.gamemode.*:
    description: Allows users to set their game mode to anything.
    default: op
    children:
      atomic-core.gamemode.adventure: true
      atomic-core.gamemode.survival: true
      atomic-core.gamemode.creative: true
      atomic-core.gamemode.spectator: true
  atomic-core.gamemode.adventure:
    description: Allows users to set thier game mode to adventure.
    default: op
  atomic-core.gamemode.survival:
    description: Allows users to set their game mode to survival.
    default: op
  atomic-core.gamemode.creative:
    description: Allows users to set their game mode to creative.
    default: op
  atomic-core.gamemode.spectator:
    description: Allows users to set their game mode to spectator.
    default: op
  atomic-core.gamemode.others:
    description: Allows users to set other user's game modes.
    default: op

  atomic-core.god:
    description: Gives access to the god command.
    default: op

  atomic-core.heal:
    description: Gives access to the heal command.
    default: op

  atomic-core.item:
    description: Gives access to the item command.
    default: op
  atomic-core.item.others:
    description: Allows players to give items to other players.
    default: op

  atomic-core.jump:
    description: Gives access to the jump command.
    default: op

  atomic-core.kill:
    description: Gives access to the kill command.
    default: op

  atomic-core.killall:
    description: Gives access to the killall command.
    default: op
  atomic-core.killall.world:
    description: Allows player to kill all entities in the current world.
    default: op

  atomic-core.level:
    description: Gives access to the level command.
    default: op

  atomic-core.listen:
    description: Gives access to the listen command.
    default: op

  atomic-core.message:
    description: Gives access to the message command.
    default: true
  atomic-core.message.reply:
    description: Gives access to the reply command.
    default: true

  atomic-core.nick:
    description: Gives access to the nick command.
    default: op
  atomic-core.nick.others:
    description: Allows players to set the nickname of other players.
    default: op

  atomic-core.ping:
    description: Gives access to the ping command.
    default: true
  atomic-core.ping.others:
    description: Allows a player to get another player's ping.
    default: op

  atomic-core.position:
    description: Gives access to the position command.
    default: true
  atomic-core.position.others:
    description: Allows a player to get another player's position.
    default: op

  atomic-core.speed:
    description: Gives access to the speed command.
    default: op

  atomic-core.sudo:
    description: Gives access to the sudo command.
    default: false

  atomic-core.suicide:
    description: Gives access to the suicide command.
    default: op

  atomic-core.tp:
    description: Gives access to the tp command.
    default: true
  atomic-core.tp.all:
    description: Gives access to the tpall command.
    default: false
  atomic-core.tp.here:
    description: Gives access to the tphere command.
    default: op
  atomic-core.tp.others:
    description: Allows a user to teleport other players.
    default: op
  atomic-core.tp.pos:
    description: Gives access to the tppos command.
    default: op
  atomic-core.tp.request:
    description: Gives access to tpa, tpyes and tpno.
    default: true
  atomic-core.tp.silent:
    description: Allows a user to teleport silently.
    default: op


  atomic-core.warp:
    description: Gives access to the warp command.
    default: op