name: atomic-core
description: A core plugin designed for the Atomic Hive Minecraft server.
main: net.atomichive.core.Main
version: 0.0.7
authors: [Sean Bailey, Quinster]
website: http://atomichive.net

commands:
  entity:
    description: Used to manage Atomic Entities.
    usage: /entity [reload|list|spawn]
    aliases: [ae]
  fly:
    description: Toggles whether a player can fly.
    usage: /fly [player]
  gamemode:
    description: Updates a player's game mode.
    usage: /gamemode <mode> [player]
    aliases: [gm, mode]
  kill:
    description: Kills a player.
    usage: /kill <player>
  killall:
    description: Kills all entities, except players.
    usage: /killall [radius]
  level:
    description: A debug command for setting a players level.
    usage: /level <value>
  ping:
    description: Returns the delay between a players and the server in milliseconds.
    usage: /ping [player]
    aliases: [delay]
  speed:
    description: Change your flying or walking speeds.
    usage: /speed <value>
  suicide:
    description: Causes the player to spontaneously combust.
    usage: /suicide
    aliases: [sepaku]
  teleport:
    description: Teleports one player to another.
    usage: /tp [source] <destination>
    aliases: [tp, tpsilent]
  tphere:
    description: Teleports another player to you.
    usage: /tphere <player>
    aliases: [tph]
  warp:
    description: Designate a warp destination, or warp somewhere.
    usage: /warp [list|add|remove] [warp]
    aliases: [warps]

permissions:
  atomic-core.*:
    description: Gives access to all atomic-core commands.
    children:
      atomic-core.atomic-entity: true
      atomic-core.fly: true
      atomic-core.fly.other: true
      atomic-core.gamemode: true
      atomic-core.gamemode.*: true
      atomic-core.gamemode.others: true
      atomic-core.kill: true
      atomic-core.killall: true
      atomic-core.killall.world: true
      atomic-core.level: true
      atomic-core.ping: true
      atomic-core.ping.others: true
      atomic-core.speed: true
      atomic-core.suicide: true
      atomic-core.tp: true
      atomic-core.tp.others: true
      atomic-core.tp.silent: true
      atomic-core.tphere: true
      atomic-core.warp: true

  atomic-core.atomic-entity:
    description: Gives access to the entity command.
    default: op

  atomic-core.fly:
    description: Gives access to the fly command.
    default: op
  atomic-core.fly.others:
    description: Allows a user to toggle whether a different player can fly.
    default: op

  atomic-core.gamemode:
    description: Sets a users game mode.
    default: op
  atomic-core.gamemode.*:
    description: Allows users to set their game mode to anything.
    default: op
    children:
      atomic-core.gamemode.adventure: true
      atomic-core.gamemode.survival: true
      atomic-core.gamemode.creative: true
      atomic-core.gamemode.spectator: true
  atomic-core.gamemode.adventure:
    description: Allows users to set thier game mode to adventure.
    default: op
  atomic-core.gamemode.survival:
    description: Allows users to set their game mode to survival.
    default: op
  atomic-core.gamemode.creative:
    description: Allows users to set their game mode to creative.
    default: op
  atomic-core.gamemode.spectator:
    description: Allows users to set their game mode to spectator.
    default: op
  atomic-core.gamemode.others:
    description: Allows users to set other user's game modes.
    default: op

  atomic-core.kill:
    description: Gives access to the kill command.
    default: op

  atomic-core.killall:
    description: Gives access to the killall command.
    default: op
  atomic-core.killall.world:
    description: Allows player to kill all entities in the current world.
    default: op

  atomic-core.level:
    description: Gives access to the level command.
    default: op

  atomic-core.ping:
    description: Gives access to the ping command.
    default: true
  atomic-core.ping.others:
    description: Allows a player to get another player's ping.
    default: op

  atomic-core.speed:
    description: Gives access to the speed command.
    default: op

  atomic-core.suicide:
    description: Gives access to the suicide command.
    default: op

  atomic-core.tp:
    description: Gives access to the tp command.
    default: true
  atomic-core.tp.others:
    description: Allows a user to teleport other players.
    default: op
  atomic-core.tp.silent:
    description: Allows a user to teleport silently.
    default: op

  atomic-core.tphere:
    description: Gives access to the tphere command.
    default: op

  atomic-core.warp:
    description: Gives access to the warp command.
    default: op